#!/bin/bash
# Tests for scripts/bash/check_scoped_tree.sh, scripts/bash/scope_plugin_dependencies.sh, the
# scope-dependencies action and .github/workflows/plugin-vendored-deps-update.yml.
# Usage: bash tests/vendored_deps_update_test.sh
#
# The check exists because the scoping pipeline reports success on output it did not produce, so
# every tree case here is one that looks finished and is not.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHECK="$ROOT/scripts/bash/check_scoped_tree.sh"
SCOPE="$ROOT/scripts/bash/scope_plugin_dependencies.sh"
WORKFLOW="$ROOT/.github/workflows/plugin-vendored-deps-update.yml"
ACTION="$ROOT/actions/scope-dependencies/action.yml"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

tests=0
failures=()

PROXY='<?php
/* this file was generated by the matomo-scoper tool */
'

# A committed plugin whose tree is correct, then an updated lock and a rescoped file on top.
make_plugin() {
  local dir="$WORK/$1"
  rm -rf "$dir"
  mkdir -p "$dir/vendor/prefixed/foo/src" "$dir/vendor/prefixed/vendor/composer"
  printf '%s' "$PROXY" > "$dir/vendor/autoload.php"
  printf '<?php\nnamespace Matomo\\Dependencies\\Foo\\Bar;\n' > "$dir/vendor/prefixed/foo/src/Bar.php"
  printf '<?php\nnamespace Composer\\Autoload;\n' > "$dir/vendor/prefixed/vendor/composer/ClassLoader.php"
  printf '{"content-hash":"a","packages":[{"name":"foo/bar","version":"1.0.0"}]}\n' > "$dir/composer.lock"
  git -C "$dir" init -q
  git -C "$dir" add composer.lock vendor
  git -C "$dir" -c user.email=t@t -c user.name=t commit -qm base
  printf '{"content-hash":"b","packages":[{"name":"foo/bar","version":"1.1.0"}]}\n' > "$dir/composer.lock"
  printf '<?php\nnamespace Matomo\\Dependencies\\Foo\\Bar;\n// 1.1.0\n' > "$dir/vendor/prefixed/foo/src/Bar.php"
  echo "$dir"
}

expect() {
  local description="$1" want="$2" dir="$3" pattern="$4"
  shift 4
  tests=$((tests + 1))
  local output status
  output=$(bash "$CHECK" "$dir" Foo "$@" 2>&1)
  status=$?
  if [ "$status" -ne "$want" ]; then
    echo "FAIL - $description (exited $status, wanted $want): $output"
    failures+=("$description")
  elif [ -n "$pattern" ] && ! printf '%s' "$output" | grep -q -- "$pattern"; then
    echo "FAIL - $description (output did not match $pattern): $output"
    failures+=("$description")
  else
    echo "ok - $description"
  fi
}

dir=$(make_plugin good)
expect "a rescoped tree passes" 0 "$dir" '' 'Composer\Autoload'

expect "Composer's autoloader namespace fails when it is not allowed" 1 "$dir" 'Composer\\Autoload, outside'

dir=$(make_plugin stock-autoload)
printf '<?php\n// autoload.php @generated by Composer\n' > "$dir/vendor/autoload.php"
expect "the stock Composer autoloader in place of the proxy fails" 1 "$dir" 'not the matomo-scoper proxy' 'Composer\Autoload'

dir=$(make_plugin unprefixed)
printf '<?php\nnamespace GuzzleHttp\\Psr7;\n' > "$dir/vendor/prefixed/foo/src/Leak.php"
expect "a file the scoper copied through unprefixed fails" 1 "$dir" 'namespace GuzzleHttp\\Psr7, outside' 'Composer\Autoload'

dir=$(make_plugin lookalike)
printf '<?php\nnamespace ComposerX\\Thing;\n' > "$dir/vendor/prefixed/foo/src/Lookalike.php"
expect "an allowed namespace does not also allow one that merely starts with its name" 1 "$dir" 'ComposerX\\Thing' 'Composer'

dir=$(make_plugin digits)
printf '<?php\nnamespace Matomo\\Dependencies\\Foo\\V2;\nnamespace ComposerV2\\X;\n' > "$dir/vendor/prefixed/foo/src/V2.php"
expect "a namespace containing digits is read whole" 1 "$dir" 'namespace ComposerV2\\X, outside' 'Composer\Autoload'

dir=$(make_plugin other-plugin)
printf '<?php\nnamespace Matomo\\Dependencies\\FooBar\\X;\n' > "$dir/vendor/prefixed/foo/src/X.php"
expect "another plugin's prefix is not this plugin's" 1 "$dir" 'FooBar' 'Composer\Autoload'

dir=$(make_plugin stale)
git -C "$dir" checkout -q -- vendor/prefixed
expect "a new lock over the old prefixed tree fails" 1 "$dir" 'is stale' 'Composer\Autoload'

dir=$(make_plugin metadata-only)
git -C "$dir" checkout -q -- vendor/prefixed
printf '{"content-hash":"c","packages":[{"name":"foo/bar","version":"1.0.0"}]}\n' > "$dir/composer.lock"
expect "a lock that changed only its metadata does not need a new tree" 0 "$dir" '' 'Composer\Autoload'

dir=$(make_plugin new-file-only)
git -C "$dir" checkout -q -- vendor/prefixed
printf '<?php\nnamespace Matomo\\Dependencies\\Foo\\New;\n' > "$dir/vendor/prefixed/foo/src/New.php"
expect "a tree whose only change is a new file counts as regenerated" 0 "$dir" '' 'Composer\Autoload'

dir=$(make_plugin moved-reference)
git -C "$dir" checkout -q -- vendor/prefixed
printf '{"packages":[{"name":"foo/bar","version":"1.0.0","source":{"reference":"def"}}]}\n' > "$dir/composer.lock"
expect "a branch dependency that moved to a new commit at the same version needs a new tree" 1 "$dir" 'is stale' 'Composer\Autoload'

dir=$(make_plugin moved-dist)
git -C "$dir" checkout -q -- vendor/prefixed
printf '{"packages":[{"name":"foo/bar","version":"1.0.0","dist":{"url":"https://example.org/foo.zip"}}]}\n' > "$dir/composer.lock"
expect "a package whose download changed at the same version needs a new tree" 1 "$dir" 'is stale' 'Composer\Autoload'

dir=$(make_plugin renamed-repository)
git -C "$dir" checkout -q -- vendor/prefixed
printf '{"packages":[{"name":"foo/bar","version":"1.0.0","source":{"url":"https://github.com/old/bar.git","reference":"abc"},"dist":{"url":"https://api.github.com/repos/old/bar/zipball/abc","reference":"abc"}}]}\n' > "$dir/composer.lock"
git -C "$dir" -c user.email=t@t -c user.name=t commit -qam old-urls
sed -i 's#/old/#/new/#g' "$dir/composer.lock"
expect "a repository renamed with the code left as it was does not need a new tree" 0 "$dir" '' 'Composer\Autoload'

dir=$(make_plugin binary)
printf '<?php\nnamespace GuzzleHttp\\Leak;\necho "\0";\n' > "$dir/vendor/prefixed/foo/src/Binary.php"
expect "a file holding binary strings is still checked" 1 "$dir" 'namespace GuzzleHttp\\Leak, outside' 'Composer\Autoload'

dir=$(make_plugin staged)
git -C "$dir" add vendor/prefixed
expect "a rebuild that is already staged counts as regenerated" 0 "$dir" '' 'Composer\Autoload'

dir=$(make_plugin empty)
rm -rf "$dir/vendor/prefixed"/*
expect "a prefixed tree with no namespaces at all fails" 1 "$dir" 'no namespace declarations' 'Composer\Autoload'

# The downgrade target, from the script's dry run, which stops before anything is installed.
expect_downgrade() {
  local description="$1" matomo_constraint="$2" input="$3" want="$4"
  tests=$((tests + 1))
  local dir="$WORK/downgrade" got
  rm -rf "$dir"
  mkdir -p "$dir"
  if [ -n "$matomo_constraint" ]; then
    jq -n --arg c "$matomo_constraint" '{name: "Foo", require: {matomo: $c}}' > "$dir/plugin.json"
  else
    echo '{"name": "Foo"}' > "$dir/plugin.json"
  fi
  : > "$WORK/output"
  if ! GITHUB_OUTPUT="$WORK/output" bash "$SCOPE" --dry-run --downgrade-php="$input" "$dir" > /dev/null 2>&1; then
    got=error
  else
    got=$(sed -n 's/^downgrade=//p' "$WORK/output")
  fi
  if [ "$got" = "$want" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got '$got', wanted '$want')"
    failures+=("$description")
  fi
}

expect_downgrade "a Matomo 6 plugin is transpiled to 8.1" '>=6.0.0-b1,<7.0.0-b1' auto 8.1
expect_downgrade "a Matomo 5 plugin is transpiled to 7.3" '>=5.0.0-b1,<6.0.0-b1' auto 7.3
expect_downgrade "a plugin that spans Matomo 5 and 6 is transpiled for 5" '>=5.0.0,<7.0.0-b1' auto 7.3
expect_downgrade "a plugin with no Matomo requirement gets the lower target" '' auto 7.3
expect_downgrade "none skips Rector" '>=6.0.0-b1,<7.0.0-b1' none ''
expect_downgrade "an explicit target overrides plugin.json" '>=6.0.0-b1,<7.0.0-b1' 7.3 7.3
expect_downgrade "a target the Rector config does not know fails" '>=6.0.0-b1,<7.0.0-b1' 8.2 error
expect_downgrade "the lowest of several ranges decides when it comes first" '>=5.0.0-b1,<6.0.0-b1 || >=6.0.0-b1,<7.0.0-b1' auto 7.3
expect_downgrade "the lowest of several ranges decides when it comes last" '>=6.0.0-b1,<7.0.0-b1 || >=5.0.0-b1,<6.0.0-b1' auto 7.3

tests=$((tests + 1))
echo '{"name": "Foo", "require": {"matomo": "^6.0"}}' > "$WORK/downgrade/plugin.json"
if bash "$SCOPE" --dry-run "$WORK/downgrade" 2>&1 | grep -q '::warning::No >=N. bound'; then
  echo "ok - a requirement with no >=N. bound warns that the lower target was assumed"
else
  echo "FAIL - a requirement with no >=N. bound warns that the lower target was assumed"
  failures+=("the no-bound warning")
fi

expect_usage_error() {
  local description="$1"
  shift
  tests=$((tests + 1))
  if bash "$SCOPE" --dry-run "$@" > /dev/null 2>&1; then
    echo "FAIL - $description (exited 0)"
    failures+=("$description")
  else
    echo "ok - $description"
  fi
}

expect_usage_error "an unknown option is refused rather than ignored" --downgrade=none "$WORK/downgrade"
expect_usage_error "a second plugin directory is refused rather than silently winning" "$WORK/downgrade" "$WORK/downgrade"

# The action's own step, run against a stand-in script, so the arguments it builds are what is tested.
tests=$((tests + 1))
fake="$WORK/fake-repo"
mkdir -p "$fake/actions/scope-dependencies" "$fake/scripts/bash"
printf '#!/bin/bash\nprintf "%%s\\n" "$@"\n' > "$fake/scripts/bash/scope_plugin_dependencies.sh"
python3 - "$ACTION" > "$WORK/action-step.sh" <<'PY'
import sys
import yaml

print(yaml.safe_load(open(sys.argv[1]))['runs']['steps'][0]['run'])
PY
got=$(GITHUB_ACTION_PATH="$fake/actions/scope-dependencies" PLUGIN_PATH=plugin DOWNGRADE_INPUT=none \
  ALLOWED=$'Composer\\Autoload\n  GPBMetadata ' SCOPER_REF=v1 TOOLS=/t bash -e "$WORK/action-step.sh" 2>&1)
want=$'--downgrade-php=none\n--scoper-ref=v1\n--tools-dir=/t\n--allow-namespace=Composer\\Autoload\n--allow-namespace=GPBMetadata\nplugin'
if [ "$got" = "$want" ]; then
  echo "ok - the action passes each allowed namespace, and the plugin path last, to the script"
else
  echo "FAIL - the action passes each allowed namespace, and the plugin path last, to the script (got: $got)"
  failures+=("the action passes its inputs to the script")
fi

# The guards the script leans on. Each of these has a failure that looks like success.
expect_true() {
  local description="$1"
  shift
  tests=$((tests + 1))
  if "$@"; then
    echo "ok - $description"
  else
    echo "FAIL - $description"
    failures+=("$description")
  fi
}
code=$(grep -vE '^[[:space:]]*(#|$)' "$SCOPE")
line_of() {
  printf '%s\n' "$code" | grep -nE -- "$1" | cut -d: -f1
}
xdebug_line=$(line_of '^export XDEBUG_MODE=off$')
first_php_line=$(line_of '(^|[[:space:]!])(php|composer) ' | head -1)
expect_true "Xdebug is off before the script runs any PHP" [ "${xdebug_line:-999}" -lt "${first_php_line:-0}" ]
scope_line=$(line_of 'bin/matomo-scoper" scope')
phar_check_line=$(line_of '^[[:space:]]*if ! phar_intact "[^"]*phar"; then')
expect_true "the script checks php-scoper.phar before the scoper can run it" [ "${phar_check_line:-999}" -lt "${scope_line:-0}" ]
expect_true "the default scoper ref is a commit, not a branch" \
  grep -qE '^SCOPER_PINNED_REF=[0-9a-f]{40}$' "$SCOPE"
expect_true "the script checks the tree after everything that writes to it" \
  [ "$(line_of 'check_scoped_tree\.sh')" = "$(printf '%s\n' "$code" | wc -l)" ]

# The workflow's branch check, run against a stand-in gh. Each case is the answers it gives to the
# three calls: the branch lookup, the open pull requests and the comparison.
python3 - "$WORKFLOW" > "$WORK/branch-step.sh" <<'PY'
import sys
import yaml

steps = yaml.safe_load(open(sys.argv[1]))['jobs']['update']['steps']
print(next(s for s in steps if s.get('id') == 'branch')['run'])
PY
mkdir -p "$WORK/bin"
cat > "$WORK/bin/gh" <<'SH'
#!/bin/bash
case "$2" in
  */branches/*) answer="$GH_BRANCH" ;;
  */pulls\?*) answer="$GH_PULLS" ;;
  */compare/*) answer="$GH_COMPARE" ;;
esac
case "$answer" in
  fail:*) echo "${answer#fail:}" >&2; exit 1 ;;
  *) [ -n "$answer" ] && echo "$answer"; exit 0 ;;
esac
SH
chmod +x "$WORK/bin/gh"
expect_branch() {
  local description="$1" branch="$2" pulls="$3" compare="$4" want="$5"
  tests=$((tests + 1))
  local got
  : > "$WORK/branch-output"
  if ! PATH="$WORK/bin:$PATH" GITHUB_OUTPUT="$WORK/branch-output" GITHUB_REPOSITORY=matomo-org/plugin-Foo \
    BASE_BRANCH=5.x-dev UPDATE_BRANCH=automated/vendored-dependencies-5.x-dev BOT_EMAIL=bot@x \
    GH_BRANCH="$branch" GH_PULLS="$pulls" GH_COMPARE="$compare" \
    bash -eo pipefail "$WORK/branch-step.sh" > /dev/null 2>&1; then
    got=error
  else
    got=$(sed -n 's/^skip=//p' "$WORK/branch-output")
  fi
  if [ "$got" = "$want" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got '$got', wanted '$want')"
    failures+=("$description")
  fi
}
expect_branch "no update branch yet is updated" 'fail:gh: Not Found (HTTP 404)' '' '' false
expect_branch "a branch lookup that fails for another reason stops the run" 'fail:gh: Server Error (HTTP 500)' '' '' error
expect_branch "a branch left behind with no open pull request is rebuilt" '' 0 1 false
expect_branch "a pull request lookup that fails stops the run" '' 'fail:gh: Server Error (HTTP 500)' '' error
expect_branch "an open pull request with a human commit is left alone" '' 1 1 true
expect_branch "an open pull request with only the workflow's commits is refreshed" '' 1 0 false
expect_branch "a comparison that fails stops the run" '' 1 'fail:gh: Server Error (HTTP 500)' error

# The workflow's update step, with a stand-in composer that prints a canned log and leaves the lock
# that make_plugin already changed.
python3 - "$WORKFLOW" > "$WORK/update-step.sh" <<'PY'
import sys
import yaml

steps = yaml.safe_load(open(sys.argv[1]))['jobs']['update']['steps']
print(next(s for s in steps if s.get('id') == 'update')['run'])
PY
cat > "$WORK/bin/composer" <<'SH'
#!/bin/bash
printf '%s' "$COMPOSER_LOG"
SH
chmod +x "$WORK/bin/composer"
expect_summary() {
  local description="$1" log="$2" want="$3"
  tests=$((tests + 1))
  local dir got
  dir=$(make_plugin "summary")
  mkdir -p "$WORK/runner"
  : > "$WORK/update-output"
  if ! PATH="$WORK/bin:$PATH" GITHUB_OUTPUT="$WORK/update-output" RUNNER_TEMP="$WORK/runner" PLUGIN_DIR="$dir" \
    COMPOSER_LOG="$log" bash -eo pipefail "$WORK/update-step.sh" > /dev/null 2>&1; then
    got=error
  else
    got=$(cat "$WORK/runner/package-changes.md")
  fi
  if [ "$got" = "$want" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got '$got', wanted '$want')"
    failures+=("$description")
  fi
}
expect_summary "the pull request lists the packages composer changed" \
  $'Lock file operations: 0 installs, 1 update, 0 removals\n  - Upgrading foo/bar (1.0.0 => 1.1.0)\nInstalling dependencies from lock file\n  - Downloading foo/bar (1.1.0)\n' \
  '- Upgrading foo/bar (1.0.0 => 1.1.0)'
expect_summary "a change composer listed no operation for still gets a summary" \
  $'Nothing to modify in lock file\nInstalling dependencies from lock file\n' \
  "Composer listed no package operations; the \`composer.lock\` diff shows what changed."

# The workflow decides whether to rescope with the same lock comparison the checker fails on, so the
# two must not drift apart.
tests=$((tests + 1))
lock_filter() {
  grep -A1 -E '^[[:space:]]*lock_packages\(\) \{' "$1" | tail -1 | sed -E 's/^[[:space:]]+//'
}
if [ -n "$(lock_filter "$CHECK")" ] && [ "$(lock_filter "$CHECK")" = "$(lock_filter "$WORKFLOW")" ]; then
  echo "ok - the workflow and the checker compare composer.lock the same way"
else
  echo "FAIL - the workflow and the checker compare composer.lock the same way"
  failures+=("the lock comparisons match")
fi

# The workflow's guards.
yaml_output=$(python3 - "$WORKFLOW" <<'PY' 2>&1
import sys
import yaml

workflow = yaml.safe_load(open(sys.argv[1]))
jobs = workflow['jobs']
steps = jobs['update']['steps']
pr_steps = jobs['pull-request']['steps']

def check(description, condition):
    print(("ok - " if condition else "FAIL - ") + description)

def step(name, in_steps=None):
    found = [s for s in (steps if in_steps is None else in_steps) if s.get('name') == name]
    assert len(found) == 1, f"expected one step named {name!r}, found {len(found)}"
    return found[0]

check("setup-php loads no coverage driver", step('Setup PHP')['with'].get('coverage') == 'none')

scope = step('Scope, downgrade and check')
this_repo = step('Check out plugin-ci-workflows repository')
check("the action comes from the checkout at workflows-ref, not a fixed ref",
      scope['uses'] == './.plugin-ci-workflows/actions/scope-dependencies'
      and this_repo['with']['path'] == '.plugin-ci-workflows'
      and this_repo['with']['ref'] == '${{ inputs.workflows-ref }}')

order = [s.get('name') for s in steps]
check("the tree is checked before it is packaged for the pull request",
      order.index('Scope, downgrade and check') < order.index('Upload the rebuilt tree'))

checkouts = [s for s in steps + pr_steps if str(s.get('uses', '')).startswith('actions/checkout@')]
check("no checkout leaves credentials in a git config the scoped tree is committed next to",
      len(checkouts) == 3 and all(s.get('with', {}).get('persist-credentials') is False for s in checkouts))

writes = lambda job: [k for k, v in (job.get('permissions') or {}).items() if v == 'write']
check("the job that runs dependency code holds no write permission", writes(jobs['update']) == [])
check("only the pull-request job can write, and it runs after the update job",
      jobs['pull-request'].get('needs') == 'update' and workflow.get('permissions') == {'contents': 'read'})
pr_runs = ' '.join(s.get('run', '') for s in pr_steps)
pr_uses = ' '.join(s.get('uses', '') for s in pr_steps)
check("the pull-request job runs no composer, php or scoper",
      'composer ' not in pr_runs and 'php ' not in pr_runs
      and 'scope-dependencies' not in pr_uses and 'setup-php' not in pr_uses)

pr = step('Open or update the pull request', pr_steps)['with']
check("the workflow's commits are authored by the address the human-commit check filters on",
      '${{ env.BOT_EMAIL }}' in pr['author'] and '${{ env.BOT_EMAIL }}' in pr['committer'])
check("the human-commit check runs before anything is rebuilt",
      order.index('Check the update branch has no human commits') < order.index('Update dependencies'))
PY
)
yaml_status=$?
printf '%s\n' "$yaml_output"
while IFS= read -r line; do
  tests=$((tests + 1))
  case "$line" in
    "FAIL - "*) failures+=("${line#FAIL - }") ;;
  esac
done < <(printf '%s\n' "$yaml_output" | grep -E '^(ok|FAIL) - ')
# A traceback prints no FAIL line, so without this a renamed step would pass the suite having
# asserted nothing.
if [ "$yaml_status" -ne 0 ]; then
  tests=$((tests + 1))
  echo "FAIL - the workflow invariants block ran to completion (exited $yaml_status)"
  failures+=("the workflow invariants block ran to completion")
fi

echo
echo "$tests tests, ${#failures[@]} failures"
[ ${#failures[@]} -eq 0 ] || exit 1
