#!/bin/bash
# Tests for scripts/bash/check_scoped_tree.sh, scripts/bash/scope_plugin_dependencies.sh, the
# scope-dependencies action and .github/workflows/plugin-vendored-deps-update.yml.
# Usage: bash tests/vendored_deps_update_test.sh
#
# The check exists because the scoping pipeline reports success on output it did not produce, so
# every tree case here is one that looks finished and is not.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHECK="$ROOT/scripts/bash/check_scoped_tree.sh"
SCOPE="$ROOT/scripts/bash/scope_plugin_dependencies.sh"
WORKFLOW="$ROOT/.github/workflows/plugin-vendored-deps-update.yml"
ACTION="$ROOT/actions/scope-dependencies/action.yml"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

tests=0
failures=()

PROXY='<?php
/* this file was generated by the matomo-scoper tool */
'

# A committed plugin whose tree is correct, then an updated lock and a rescoped file on top.
make_plugin() {
  local dir="$WORK/$1"
  rm -rf "$dir"
  mkdir -p "$dir/vendor/prefixed/foo/src" "$dir/vendor/prefixed/vendor/composer"
  printf '%s' "$PROXY" > "$dir/vendor/autoload.php"
  printf '<?php\nnamespace Matomo\\Dependencies\\Foo\\Bar;\n' > "$dir/vendor/prefixed/foo/src/Bar.php"
  printf '<?php\nnamespace Composer\\Autoload;\n' > "$dir/vendor/prefixed/vendor/composer/ClassLoader.php"
  printf '{"content-hash":"a","packages":[{"name":"foo/bar","version":"1.0.0"}]}\n' > "$dir/composer.lock"
  git -C "$dir" init -q
  git -C "$dir" add composer.lock vendor
  git -C "$dir" -c user.email=t@t -c user.name=t commit -qm base
  printf '{"content-hash":"b","packages":[{"name":"foo/bar","version":"1.1.0"}]}\n' > "$dir/composer.lock"
  printf '<?php\nnamespace Matomo\\Dependencies\\Foo\\Bar;\n// 1.1.0\n' > "$dir/vendor/prefixed/foo/src/Bar.php"
  echo "$dir"
}

expect() {
  local description="$1" want="$2" dir="$3" pattern="$4"
  shift 4
  tests=$((tests + 1))
  local output status
  output=$(bash "$CHECK" "$dir" Foo "$@" 2>&1)
  status=$?
  if [ "$status" -ne "$want" ]; then
    echo "FAIL - $description (exited $status, wanted $want): $output"
    failures+=("$description")
  elif [ -n "$pattern" ] && ! printf '%s' "$output" | grep -q -- "$pattern"; then
    echo "FAIL - $description (output did not match $pattern): $output"
    failures+=("$description")
  else
    echo "ok - $description"
  fi
}

dir=$(make_plugin good)
expect "a rescoped tree passes" 0 "$dir" '' 'Composer\Autoload'

expect "Composer's autoloader namespace fails when it is not allowed" 1 "$dir" 'Composer\\Autoload, outside'

dir=$(make_plugin stock-autoload)
printf '<?php\n// autoload.php @generated by Composer\n' > "$dir/vendor/autoload.php"
expect "the stock Composer autoloader in place of the proxy fails" 1 "$dir" 'not the matomo-scoper proxy' 'Composer\Autoload'

dir=$(make_plugin unprefixed)
printf '<?php\nnamespace GuzzleHttp\\Psr7;\n' > "$dir/vendor/prefixed/foo/src/Leak.php"
expect "a file the scoper copied through unprefixed fails" 1 "$dir" 'namespace GuzzleHttp\\Psr7, outside' 'Composer\Autoload'

dir=$(make_plugin unprefixed-inline)
printf '<?php namespace  GuzzleHttp\\Psr7 {\n}\n' > "$dir/vendor/prefixed/foo/src/Leak.php"
expect "an unprefixed namespace declared on the <?php line fails" 1 "$dir" 'namespace GuzzleHttp\\Psr7, outside' 'Composer\Autoload'

dir=$(make_plugin lookalike)
printf '<?php\nnamespace ComposerX\\Thing;\n' > "$dir/vendor/prefixed/foo/src/Lookalike.php"
expect "an allowed namespace does not also allow one that merely starts with its name" 1 "$dir" 'ComposerX\\Thing' 'Composer'

dir=$(make_plugin digits)
printf '<?php\nnamespace Matomo\\Dependencies\\Foo\\V2;\nnamespace ComposerV2\\X;\n' > "$dir/vendor/prefixed/foo/src/V2.php"
expect "a namespace containing digits is read whole" 1 "$dir" 'namespace ComposerV2\\X, outside' 'Composer\Autoload'

dir=$(make_plugin other-plugin)
printf '<?php\nnamespace Matomo\\Dependencies\\FooBar\\X;\n' > "$dir/vendor/prefixed/foo/src/X.php"
expect "another plugin's prefix is not this plugin's" 1 "$dir" 'FooBar' 'Composer\Autoload'

dir=$(make_plugin stale)
git -C "$dir" checkout -q -- vendor/prefixed
expect "a new lock over the old prefixed tree fails" 1 "$dir" 'is stale' 'Composer\Autoload'

dir=$(make_plugin metadata-only)
git -C "$dir" checkout -q -- vendor/prefixed
printf '{"content-hash":"c","packages":[{"name":"foo/bar","version":"1.0.0"}]}\n' > "$dir/composer.lock"
expect "a lock that changed only its metadata does not need a new tree" 0 "$dir" '' 'Composer\Autoload'

dir=$(make_plugin new-file-only)
git -C "$dir" checkout -q -- vendor/prefixed
printf '<?php\nnamespace Matomo\\Dependencies\\Foo\\New;\n' > "$dir/vendor/prefixed/foo/src/New.php"
expect "a tree whose only change is a new file counts as regenerated" 0 "$dir" '' 'Composer\Autoload'

dir=$(make_plugin moved-reference)
git -C "$dir" checkout -q -- vendor/prefixed
printf '{"packages":[{"name":"foo/bar","version":"1.0.0","source":{"reference":"def"}}]}\n' > "$dir/composer.lock"
expect "a branch dependency that moved to a new commit at the same version needs a new tree" 1 "$dir" 'is stale' 'Composer\Autoload'

dir=$(make_plugin moved-dist)
git -C "$dir" checkout -q -- vendor/prefixed
printf '{"packages":[{"name":"foo/bar","version":"1.0.0","dist":{"url":"https://example.org/foo.zip"}}]}\n' > "$dir/composer.lock"
expect "a package whose download changed at the same version needs a new tree" 1 "$dir" 'is stale' 'Composer\Autoload'

dir=$(make_plugin renamed-repository)
git -C "$dir" checkout -q -- vendor/prefixed
printf '{"packages":[{"name":"foo/bar","version":"1.0.0","source":{"url":"https://github.com/old/bar.git","reference":"abc"},"dist":{"url":"https://api.github.com/repos/old/bar/zipball/abc","reference":"abc"}}]}\n' > "$dir/composer.lock"
git -C "$dir" -c user.email=t@t -c user.name=t commit -qam old-urls
sed -i 's#/old/#/new/#g' "$dir/composer.lock"
expect "a repository renamed with the code left as it was does not need a new tree" 0 "$dir" '' 'Composer\Autoload'

dir=$(make_plugin binary)
printf '<?php\nnamespace GuzzleHttp\\Leak;\necho "\0";\n' > "$dir/vendor/prefixed/foo/src/Binary.php"
expect "a file holding binary strings is still checked" 1 "$dir" 'namespace GuzzleHttp\\Leak, outside' 'Composer\Autoload'

dir=$(make_plugin staged)
git -C "$dir" add vendor/prefixed
expect "a rebuild that is already staged counts as regenerated" 0 "$dir" '' 'Composer\Autoload'

dir=$(make_plugin empty)
rm -rf "$dir/vendor/prefixed"/*
expect "a prefixed tree with no namespaces at all fails" 1 "$dir" 'no namespace declarations' 'Composer\Autoload'

# The downgrade target, from the script's dry run, which stops before anything is installed.
expect_downgrade() {
  local description="$1" matomo_constraint="$2" input="$3" want="$4"
  tests=$((tests + 1))
  local dir="$WORK/downgrade" got
  rm -rf "$dir"
  mkdir -p "$dir"
  if [ -n "$matomo_constraint" ]; then
    jq -n --arg c "$matomo_constraint" '{name: "Foo", require: {matomo: $c}}' > "$dir/plugin.json"
  else
    echo '{"name": "Foo"}' > "$dir/plugin.json"
  fi
  : > "$WORK/output"
  if ! GITHUB_OUTPUT="$WORK/output" bash "$SCOPE" --dry-run --downgrade-php="$input" "$dir" > /dev/null 2>&1; then
    got=error
  else
    got=$(sed -n 's/^downgrade=//p' "$WORK/output")
  fi
  if [ "$got" = "$want" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got '$got', wanted '$want')"
    failures+=("$description")
  fi
}

expect_downgrade "a Matomo 6 plugin is transpiled to 8.1" '>=6.0.0-b1,<7.0.0-b1' auto 8.1
expect_downgrade "a Matomo 5 plugin is transpiled to 7.3" '>=5.0.0-b1,<6.0.0-b1' auto 7.3
expect_downgrade "a plugin that spans Matomo 5 and 6 is transpiled for 5" '>=5.0.0,<7.0.0-b1' auto 7.3
expect_downgrade "a plugin with no Matomo requirement gets the lower target" '' auto 7.3
expect_downgrade "none skips Rector" '>=6.0.0-b1,<7.0.0-b1' none ''
expect_downgrade "an explicit target overrides plugin.json" '>=6.0.0-b1,<7.0.0-b1' 7.3 7.3
expect_downgrade "a target the Rector config does not know fails" '>=6.0.0-b1,<7.0.0-b1' 8.2 error
expect_downgrade "the lowest of several ranges decides when it comes first" '>=5.0.0-b1,<6.0.0-b1 || >=6.0.0-b1,<7.0.0-b1' auto 7.3
expect_downgrade "the lowest of several ranges decides when it comes last" '>=6.0.0-b1,<7.0.0-b1 || >=5.0.0-b1,<6.0.0-b1' auto 7.3
expect_downgrade "a caret requirement on Matomo 6 is transpiled to 8.1" '^6.0' auto 8.1
expect_downgrade "a tilde requirement on Matomo 5 is transpiled to 7.3" '~5.0' auto 7.3
expect_downgrade "a bound with no minor version still counts" '>=6,<7' auto 8.1

tests=$((tests + 1))
echo '{"name": "Foo", "require": {"matomo": "*"}}' > "$WORK/downgrade/plugin.json"
if bash "$SCOPE" --dry-run "$WORK/downgrade" 2>&1 | grep -q '::warning::No >=, ^ or ~ lower bound'; then
  echo "ok - a requirement with no lower bound warns that the lower target was assumed"
else
  echo "FAIL - a requirement with no lower bound warns that the lower target was assumed"
  failures+=("the no-bound warning")
fi

expect_usage_error() {
  local description="$1"
  shift
  tests=$((tests + 1))
  if bash "$SCOPE" --dry-run "$@" > /dev/null 2>&1; then
    echo "FAIL - $description (exited 0)"
    failures+=("$description")
  else
    echo "ok - $description"
  fi
}

expect_usage_error "an unknown option is refused rather than ignored" --downgrade=none "$WORK/downgrade"
expect_usage_error "a second plugin directory is refused rather than silently winning" "$WORK/downgrade" "$WORK/downgrade"

# The action's own step, run against a stand-in script, so the arguments it builds are what is tested.
tests=$((tests + 1))
fake="$WORK/fake-repo"
mkdir -p "$fake/actions/scope-dependencies" "$fake/scripts/bash"
printf '#!/bin/bash\nprintf "%%s\\n" "$@"\n' > "$fake/scripts/bash/scope_plugin_dependencies.sh"
python3 - "$ACTION" > "$WORK/action-step.sh" <<'PY'
import sys
import yaml

print(yaml.safe_load(open(sys.argv[1]))['runs']['steps'][0]['run'])
PY
got=$(GITHUB_ACTION_PATH="$fake/actions/scope-dependencies" PLUGIN_PATH=plugin DOWNGRADE_INPUT=none \
  ALLOWED=$'Composer\\Autoload\n  GPBMetadata ' SCOPER_REF=v1 TOOLS=/t bash -e "$WORK/action-step.sh" 2>&1)
want=$'--downgrade-php=none\n--scoper-ref=v1\n--tools-dir=/t\n--allow-namespace=Composer\\Autoload\n--allow-namespace=GPBMetadata\nplugin'
if [ "$got" = "$want" ]; then
  echo "ok - the action passes each allowed namespace, and the plugin path last, to the script"
else
  echo "FAIL - the action passes each allowed namespace, and the plugin path last, to the script (got: $got)"
  failures+=("the action passes its inputs to the script")
fi

# The guards the script leans on. Each of these has a failure that looks like success.
expect_true() {
  local description="$1"
  shift
  tests=$((tests + 1))
  if "$@"; then
    echo "ok - $description"
  else
    echo "FAIL - $description"
    failures+=("$description")
  fi
}
code=$(grep -vE '^[[:space:]]*(#|$)' "$SCOPE")
line_of() {
  printf '%s\n' "$code" | grep -nE -- "$1" | cut -d: -f1
}
xdebug_line=$(line_of '^export XDEBUG_MODE=off$')
first_php_line=$(line_of '(^|[[:space:]!])(php|composer) ' | head -1)
expect_true "Xdebug is off before the script runs any PHP" [ "${xdebug_line:-999}" -lt "${first_php_line:-0}" ]
scope_line=$(line_of 'bin/matomo-scoper" scope')
phar_check_line=$(line_of '^[[:space:]]*if ! phar_intact "[^"]*phar"; then')
expect_true "the script checks php-scoper.phar before the scoper can run it" [ "${phar_check_line:-999}" -lt "${scope_line:-0}" ]
expect_true "the default scoper ref is a commit, not a branch" \
  grep -qE '^SCOPER_PINNED_REF=[0-9a-f]{40}$' "$SCOPE"
expect_true "the script checks the tree after everything that writes to it" \
  [ "$(line_of 'check_scoped_tree\.sh')" = "$(printf '%s\n' "$code" | wc -l)" ]

# The workflow's branch check, run against a stand-in gh. Each case is the answers it gives to the
# three calls: the branch lookup, the open pull requests and the comparison.
python3 - "$WORKFLOW" > "$WORK/branch-step.sh" <<'PY'
import sys
import yaml

steps = yaml.safe_load(open(sys.argv[1]))['jobs']['update']['steps']
print(next(s for s in steps if s.get('id') == 'branch')['run'])
PY
mkdir -p "$WORK/bin"
cat > "$WORK/bin/gh" <<'SH'
#!/bin/bash
case "$2" in
  */branches/*) answer="$GH_BRANCH" ;;
  */pulls\?*) answer="$GH_PULLS" ;;
  */compare/*) answer="$GH_COMPARE" ;;
esac
case "$answer" in
  fail:*) echo "${answer#fail:}" >&2; exit 1 ;;
  *) [ -n "$answer" ] && echo "$answer"; exit 0 ;;
esac
SH
chmod +x "$WORK/bin/gh"
expect_branch() {
  local description="$1" branch="$2" pulls="$3" compare="$4" want="$5"
  tests=$((tests + 1))
  local got
  : > "$WORK/branch-output"
  if ! PATH="$WORK/bin:$PATH" GITHUB_OUTPUT="$WORK/branch-output" GITHUB_REPOSITORY=matomo-org/plugin-Foo \
    BASE_BRANCH=5.x-dev UPDATE_BRANCH=automated/vendored-dependencies-5.x-dev BOT_EMAIL=bot@x \
    GH_BRANCH="$branch" GH_PULLS="$pulls" GH_COMPARE="$compare" \
    bash -eo pipefail "$WORK/branch-step.sh" > /dev/null 2>&1; then
    got=error
  else
    got=$(sed -n 's/^skip=//p' "$WORK/branch-output")
  fi
  if [ "$got" = "$want" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got '$got', wanted '$want')"
    failures+=("$description")
  fi
}
expect_branch "no update branch yet is updated" 'fail:gh: Not Found (HTTP 404)' '' '' false
expect_branch "a branch lookup that fails for another reason stops the run" 'fail:gh: Server Error (HTTP 500)' '' '' error
expect_branch "a branch left behind with no open pull request is rebuilt" '' 0 1 false
expect_branch "a pull request lookup that fails stops the run" '' 'fail:gh: Server Error (HTTP 500)' '' error
expect_branch "an open pull request with a human commit is left alone" '' 1 1 true
expect_branch "an open pull request with only the workflow's commits is refreshed" '' 1 0 false
expect_branch "a comparison that fails stops the run" '' 1 'fail:gh: Server Error (HTTP 500)' error
expect_true "the branch check hands the head it saw to the pull-request job" \
  grep -qx 'head=abc123' <(: > "$WORK/branch-output"; PATH="$WORK/bin:$PATH" GITHUB_OUTPUT="$WORK/branch-output" \
    GITHUB_REPOSITORY=matomo-org/plugin-Foo BASE_BRANCH=5.x-dev UPDATE_BRANCH=u BOT_EMAIL=bot@x \
    GH_BRANCH=abc123 GH_PULLS=0 bash -eo pipefail "$WORK/branch-step.sh" > /dev/null 2>&1; cat "$WORK/branch-output")

# The pull-request job's steps that run before the push: applying the untrusted tree, and checking
# the branch has not moved.
pr_step() {
  python3 - "$WORKFLOW" "$1" <<'PY'
import sys
import yaml

steps = yaml.safe_load(open(sys.argv[1]))['jobs']['pull-request']['steps']
print(next(s for s in steps if s.get('name') == sys.argv[2])['run'])
PY
}
pr_step 'Apply the rebuilt tree' > "$WORK/apply-step.sh"
pr_step 'Check the update branch has not moved' > "$WORK/moved-step.sh"
expect_apply() {
  local description="$1" want="$2" got
  tests=$((tests + 1))
  rm -rf "$WORK/target" && mkdir -p "$WORK/target/vendor"
  git -C "$WORK/target" init -q
  echo old > "$WORK/target/vendor/gone.php"
  git -C "$WORK/target" add vendor/gone.php
  if RUNNER_TEMP="$WORK/runner" PLUGIN_DIR="$WORK/target" bash -eo pipefail "$WORK/apply-step.sh" > /dev/null 2>&1; then
    got=applied
  else
    got=refused
  fi
  if [ "$got" = "$want" ] && { [ "$got" = refused ] || [ ! -e "$WORK/target/vendor/gone.php" ]; } \
    && [ ! -e "$WORK/target/.git/hooks/pre-commit" ] && [ ! -e "$WORK/outside" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got '$got', wanted '$want')"
    failures+=("$description")
  fi
}
make_tree() {
  rm -rf "$WORK/runner" "$WORK/src" && mkdir -p "$WORK/runner/rebuilt" "$WORK/src/vendor/prefixed"
  echo '{}' > "$WORK/src/composer.lock"
  echo '<?php' > "$WORK/src/vendor/prefixed/a.php"
  (cd "$WORK/src" && tar -cf "$WORK/runner/rebuilt/tree.tar" "$@")
}
make_tree composer.lock vendor
expect_apply "a tree of composer.lock and vendor/ is applied, and a file it dropped is deleted" applied
make_tree composer.lock vendor && mkdir -p "$WORK/src/.git/hooks" && echo x > "$WORK/src/.git/hooks/pre-commit" \
  && (cd "$WORK/src" && tar -rf "$WORK/runner/rebuilt/tree.tar" .git/hooks/pre-commit)
expect_apply "a tree carrying a git hook is refused" refused
make_tree composer.lock vendor && ln -s ../../outside "$WORK/src/vendor/link" \
  && (cd "$WORK/src" && tar -rf "$WORK/runner/rebuilt/tree.tar" vendor/link)
expect_apply "a tree carrying a symlink is refused" refused
make_tree composer.lock vendor && (cd "$WORK/src" && tar -rf "$WORK/runner/rebuilt/tree.tar" --transform 's,^,vendor/../,' composer.lock)
expect_apply "a tree with a .. path is refused" refused

expect_moved() {
  local description="$1" expected="$2" branch="$3" want="$4" got
  tests=$((tests + 1))
  if PATH="$WORK/bin:$PATH" GITHUB_REPOSITORY=matomo-org/plugin-Foo UPDATE_BRANCH=u \
    EXPECTED_HEAD="$expected" GH_BRANCH="$branch" bash -eo pipefail "$WORK/moved-step.sh" > /dev/null 2>&1; then
    got=push
  else
    got=stop
  fi
  if [ "$got" = "$want" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got '$got', wanted '$want')"
    failures+=("$description")
  fi
}
expect_moved "a branch still where the update job saw it is pushed" abc123 abc123 push
expect_moved "a branch that still does not exist is created" '' 'fail:gh: Not Found (HTTP 404)' push
expect_moved "a branch someone pushed to since is left alone" abc123 def456 stop
expect_moved "a branch created since is left alone" '' def456 stop
expect_moved "a branch lookup that fails stops the push" abc123 'fail:gh: Server Error (HTTP 500)' stop

# The workflow's update step, with a stand-in composer that prints a canned log and leaves the lock
# that make_plugin already changed.
python3 - "$WORKFLOW" > "$WORK/update-step.sh" <<'PY'
import sys
import yaml

steps = yaml.safe_load(open(sys.argv[1]))['jobs']['update']['steps']
print(next(s for s in steps if s.get('id') == 'update')['run'])
PY
cat > "$WORK/bin/composer" <<'SH'
#!/bin/bash
printf '%s' "$COMPOSER_LOG"
SH
chmod +x "$WORK/bin/composer"
expect_summary() {
  local description="$1" log="$2" want="$3"
  tests=$((tests + 1))
  local dir got
  dir=$(make_plugin "summary")
  mkdir -p "$WORK/runner"
  : > "$WORK/update-output"
  if ! PATH="$WORK/bin:$PATH" GITHUB_OUTPUT="$WORK/update-output" RUNNER_TEMP="$WORK/runner" PLUGIN_DIR="$dir" \
    COMPOSER_LOG="$log" bash -eo pipefail "$WORK/update-step.sh" > /dev/null 2>&1; then
    got=error
  else
    got=$(cat "$WORK/runner/package-changes.md")
  fi
  if [ "$got" = "$want" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got '$got', wanted '$want')"
    failures+=("$description")
  fi
}
expect_summary "the pull request lists the packages composer changed" \
  $'Lock file operations: 0 installs, 1 update, 0 removals\n  - Upgrading foo/bar (1.0.0 => 1.1.0)\nInstalling dependencies from lock file\n  - Downloading foo/bar (1.1.0)\n' \
  '- Upgrading foo/bar (1.0.0 => 1.1.0)'
expect_summary "a change composer listed no operation for still gets a summary" \
  $'Nothing to modify in lock file\nInstalling dependencies from lock file\n' \
  "Composer listed no package operations; the \`composer.lock\` diff shows what changed."

# A platform-php the caller passed is set for the update only. The stand-in composer records its
# arguments and the platform composer.json has when it runs, and writes to composer.json for config as
# the real one does.
mkdir -p "$WORK/bin-platform"
cat > "$WORK/bin-platform/composer" <<'SH'
#!/bin/bash
echo "$* $(jq -c '.config.platform // null' "$PLUGIN_DIR/composer.json")" >> "$COMPOSER_CALLS"
case "$*" in
  config*) printf '{"config":{"platform":{"php":"%s"}}}\n' "${*: -1}" > "$PLUGIN_DIR/composer.json" ;;
esac
SH
chmod +x "$WORK/bin-platform/composer"
expect_platform_calls() {
  local description="$1" platform="$2" want="$3"
  tests=$((tests + 1))
  local dir got
  dir=$(make_plugin "platform")
  printf '{"require":{"foo/bar":"^1.0"}}\n' > "$dir/composer.json"
  cp "$dir/composer.json" "$WORK/composer.json.before"
  mkdir -p "$WORK/runner"
  : > "$WORK/composer-calls"
  if ! PATH="$WORK/bin-platform:$PATH" GITHUB_OUTPUT="$WORK/update-output" RUNNER_TEMP="$WORK/runner" PLUGIN_DIR="$dir" \
    COMPOSER_CALLS="$WORK/composer-calls" TEMPORARY_PLATFORM="$platform" bash -eo pipefail "$WORK/update-step.sh" > /dev/null 2>&1; then
    got=error
  elif ! cmp -s "$dir/composer.json" "$WORK/composer.json.before"; then
    got="composer.json changed: $(cat "$dir/composer.json")"
  else
    got=$(sed -E 's/ --working-dir=[^ ]+//; s/ --no-interaction --no-progress//' "$WORK/composer-calls" | paste -sd'|')
  fi
  if [ "$got" = "$want" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got '$got', wanted '$want')"
    failures+=("$description")
  fi
}
expect_platform_calls "a passed platform PHP is set for the update, then dropped from composer.json and the lock" \
  8.1.0 'config platform.php 8.1.0 null|update {"php":"8.1.0"}|update --lock --no-install --ignore-platform-req=php* --no-scripts null'
expect_platform_calls "without a passed platform PHP, composer only updates" '' 'update null'

# The stand-in above only shows the calls are made. Whether the lock really comes out without the
# temporary platform takes real composer, which the CI runner has. The restore pass must not check
# the locked package against the runner's PHP, whichever side of it the package's PHP sits.
expect_real_platform() {
  local description="$1" package_php="$2" platform="$3" requirement="${4:-php}"
  tests=$((tests + 1))
  if ! command -v composer > /dev/null; then
    if [ -n "${CI:-}" ]; then
      echo "FAIL - $description (no composer)"
      failures+=("$description")
    else
      echo "skip - $description (no composer)"
    fi
    return
  fi
  local dir got
  dir=$(make_plugin "platform-real-$platform")
  rm -rf "$WORK/capped"
  mkdir -p "$WORK/capped"
  printf '{"name":"t/capped","version":"1.0.0","require":{"%s":"%s"}}\n' "$requirement" "$package_php" > "$WORK/capped/composer.json"
  printf '{"repositories":[{"type":"path","url":"%s","options":{"symlink":false}},{"packagist.org":false}],"require":{"t/capped":"^1.0"}}\n' \
    "$WORK/capped" > "$dir/composer.json"
  rm "$dir/composer.lock"
  cp "$dir/composer.json" "$WORK/composer.json.before"
  mkdir -p "$WORK/runner"
  if ! GITHUB_OUTPUT="$WORK/update-output" RUNNER_TEMP="$WORK/runner" PLUGIN_DIR="$dir" TEMPORARY_PLATFORM="$platform" \
    bash -eo pipefail "$WORK/update-step.sh" > "$WORK/platform-real.log" 2>&1; then
    got="the update step failed: $(tail -n 3 "$WORK/platform-real.log")"
  elif ! cmp -s "$dir/composer.json" "$WORK/composer.json.before"; then
    got="composer.json changed"
  elif jq -e 'has("platform-overrides")' "$dir/composer.lock" > /dev/null; then
    got="the lock kept platform-overrides"
  elif ! composer validate --working-dir="$dir" --check-lock --no-check-publish --no-check-all > /dev/null 2>&1; then
    got="the lock does not match composer.json"
  else
    got=$(jq -r '[.packages[] | .name + " " + .version] | join(",")' "$dir/composer.lock")
  fi
  if [ "$got" = "t/capped 1.0.0" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description ($got)"
    failures+=("$description")
  fi
}
expect_real_platform "a package capped below the runner's PHP leaves a valid lock without the platform" '^7.2 || ~8.0.0' 7.2.5
# No runner has PHP 99.
expect_real_platform "a package needing more than the runner's PHP leaves a valid lock without the platform" '>=99.0' 99.0.0
expect_real_platform "a package capped by php-64bit leaves a valid lock without the platform" '^7.2 || ~8.0.0' 7.2.5 php-64bit

python3 - "$WORKFLOW" > "$WORK/platform-step.sh" <<'PY'
import sys
import yaml

steps = yaml.safe_load(open(sys.argv[1]))['jobs']['update']['steps']
print(next(s for s in steps if s.get('id') == 'platform')['run'])
PY
expect_platform() {
  local description="$1" composer_json="$2" input="$3" want_status="$4" want_output="$5"
  tests=$((tests + 1))
  local dir status got
  dir="$WORK/platform-resolve"
  mkdir -p "$dir"
  printf '%s\n' "$composer_json" > "$dir/composer.json"
  : > "$WORK/platform-output"
  GITHUB_OUTPUT="$WORK/platform-output" PLUGIN_DIR="$dir" PHP_VERSION=8.3 PLATFORM_INPUT="$input" \
    bash -eo pipefail "$WORK/platform-step.sh" > /dev/null 2>&1
  status=$?
  got=$(cat "$WORK/platform-output")
  if [ "$status" -eq "$want_status" ] && [ "$got" = "$want_output" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (exited $status, output '$got')"
    failures+=("$description")
  fi
}
expect_platform "a pin in composer.json is used as it is" '{"config":{"platform":{"php":"8.1.0"}}}' '' 0 ''
expect_platform "a pin in composer.json written as a number is used as it is" '{"config":{"platform":{"php":8.1}}}' '' 0 ''
expect_platform "a pin in composer.json takes precedence over platform-php" '{"config":{"platform":{"php":"8.1.0"}}}' 8.2.0 0 ''
expect_platform "platform-php is set for the update when composer.json has no pin" '{}' 8.1.0 0 'temporary=8.1.0'
expect_platform "neither a pin nor platform-php fails the run" '{}' '' 1 ''
expect_platform "a platform-php that is not a version fails the run" '{}' $'8.1.0\nfoo=bar' 1 ''
expect_platform "a platform-php a pin overrides is not checked" '{"config":{"platform":{"php":"8.1.0"}}}' 'eight' 0 ''
expect_no_command() {
  local description="$1" composer_json="$2" input="$3"
  tests=$((tests + 1))
  printf '%s\n' "$composer_json" > "$WORK/platform-resolve/composer.json"
  GITHUB_OUTPUT="$WORK/platform-output" PLUGIN_DIR="$WORK/platform-resolve" PHP_VERSION=8.3 PLATFORM_INPUT="$input" \
    bash -eo pipefail "$WORK/platform-step.sh" > "$WORK/platform-stdout" 2>&1
  if grep -qE $'(^|\r)::stop-commands' "$WORK/platform-stdout"; then
    echo "FAIL - $description"
    failures+=("$description")
  else
    echo "ok - $description"
  fi
}
expect_no_command "a newline in platform-php starts no workflow command beside a pin" '{"config":{"platform":{"php":"8.1.0"}}}' $'eight\n::stop-commands::x'
expect_no_command "a newline in platform-php starts no workflow command" '{}' $'eight\n::stop-commands::x'
expect_no_command "a carriage return in platform-php starts no workflow command" '{}' $'eight\r::stop-commands::x'
expect_no_command "a line break in the composer.json pin starts no workflow command" '{"config":{"platform":{"php":"8.1.0\r\n::stop-commands::x"}}}' 8.2.0

expect_platform_warning() {
  local description="$1" pin="$2" input="$3" want="$4"
  tests=$((tests + 1))
  local got
  printf '{"config":{"platform":{"php":"%s"}}}\n' "$pin" > "$WORK/platform-resolve/composer.json"
  got=$(GITHUB_OUTPUT=/dev/null PLUGIN_DIR="$WORK/platform-resolve" PHP_VERSION=8.3 PLATFORM_INPUT="$input" \
    bash -eo pipefail "$WORK/platform-step.sh" 2>&1 | grep -c '^::warning.*Ignoring platform-php')
  if [ "$got" = "$want" ]; then
    echo "ok - $description"
  else
    echo "FAIL - $description (got $got warnings, wanted $want)"
    failures+=("$description")
  fi
}
expect_platform_warning "a platform-php that differs from the composer.json pin is warned about" 8.1.0 8.2.0 1
expect_platform_warning "8.1 and a pin of 8.1.0 are the same platform" 8.1.0 8.1 0

# The workflow decides whether to rescope with the same lock comparison the checker fails on, so the
# two must not drift apart.
tests=$((tests + 1))
lock_filter() {
  grep -A1 -E '^[[:space:]]*lock_packages\(\) \{' "$1" | tail -1 | sed -E 's/^[[:space:]]+//'
}
if [ -n "$(lock_filter "$CHECK")" ] && [ "$(lock_filter "$CHECK")" = "$(lock_filter "$WORKFLOW")" ]; then
  echo "ok - the workflow and the checker compare composer.lock the same way"
else
  echo "FAIL - the workflow and the checker compare composer.lock the same way"
  failures+=("the lock comparisons match")
fi

# The workflow's guards.
yaml_output=$(python3 - "$WORKFLOW" <<'PY' 2>&1
import sys
import yaml

workflow = yaml.safe_load(open(sys.argv[1]))
jobs = workflow['jobs']
steps = jobs['update']['steps']
pr_steps = jobs['pull-request']['steps']

def check(description, condition):
    print(("ok - " if condition else "FAIL - ") + description)

def step(name, in_steps=None):
    found = [s for s in (steps if in_steps is None else in_steps) if s.get('name') == name]
    assert len(found) == 1, f"expected one step named {name!r}, found {len(found)}"
    return found[0]

check("setup-php loads no coverage driver", step('Setup PHP')['with'].get('coverage') == 'none')

scope = step('Scope, downgrade and check')
this_repo = step('Check out plugin-ci-workflows repository')
check("the action comes from the checkout at workflows-ref, not a fixed ref",
      scope['uses'] == './.plugin-ci-workflows/actions/scope-dependencies'
      and this_repo['with']['path'] == '.plugin-ci-workflows'
      and this_repo['with']['ref'] == '${{ inputs.workflows-ref }}')

order = [s.get('name') for s in steps]
check("the tree is checked before it is packaged for the pull request",
      order.index('Scope, downgrade and check') < order.index('Upload the rebuilt tree'))

checkouts = [s for s in steps + pr_steps if str(s.get('uses', '')).startswith('actions/checkout@')]
check("no checkout leaves credentials in a git config the scoped tree is committed next to",
      len(checkouts) == 3 and all(s.get('with', {}).get('persist-credentials') is False for s in checkouts))

writes = lambda job: [k for k, v in (job.get('permissions') or {}).items() if v == 'write']
check("the job that runs dependency code holds no write permission", writes(jobs['update']) == [])
check("only the pull-request job can write, and it runs after the update job",
      jobs['pull-request'].get('needs') == 'update' and workflow.get('permissions') == {'contents': 'read'})
pr_runs = ' '.join(s.get('run', '') for s in pr_steps)
pr_uses = ' '.join(s.get('uses', '') for s in pr_steps)
check("the pull-request job runs no composer, php or scoper",
      'composer ' not in pr_runs and 'php ' not in pr_runs
      and 'scope-dependencies' not in pr_uses and 'setup-php' not in pr_uses)

check("each branch of a matrix caller uploads and downloads its own artifact",
      step('Upload the rebuilt tree')['with']['name'] == '${{ steps.update.outputs.artifact }}'
      and step('Download the rebuilt tree', pr_steps)['with']['name'] == '${{ needs.update.outputs.artifact }}'
      and 'artifact=rebuilt-tree-${BASE_BRANCH' in step('Update dependencies')['run'])

update_run = step('Update dependencies')['run']
check("the commit the pull-request job checks out is read before composer can move HEAD",
      0 <= update_run.find('base=$(git') < update_run.find('composer update')
      and 'base-sha=$base' in update_run and 'rev-parse HEAD)" >> ' not in update_run)

pr = step('Open or update the pull request', pr_steps)['with']
check("the workflow's commits are authored by the address the human-commit check filters on",
      '${{ env.BOT_EMAIL }}' in pr['author'] and '${{ env.BOT_EMAIL }}' in pr['committer'])
check("the human-commit check runs before anything is rebuilt",
      order.index('Check the update branch has no human commits') < order.index('Update dependencies'))
PY
)
yaml_status=$?
printf '%s\n' "$yaml_output"
while IFS= read -r line; do
  tests=$((tests + 1))
  case "$line" in
    "FAIL - "*) failures+=("${line#FAIL - }") ;;
  esac
done < <(printf '%s\n' "$yaml_output" | grep -E '^(ok|FAIL) - ')
# A traceback prints no FAIL line, so without this a renamed step would pass the suite having
# asserted nothing.
if [ "$yaml_status" -ne 0 ]; then
  tests=$((tests + 1))
  echo "FAIL - the workflow invariants block ran to completion (exited $yaml_status)"
  failures+=("the workflow invariants block ran to completion")
fi

echo
echo "$tests tests, ${#failures[@]} failures"
[ ${#failures[@]} -eq 0 ] || exit 1
