#!/bin/bash
# Checks that a regenerated vendor/prefixed tree is really the output of this run.
#
# Every one of these has shipped, or nearly shipped, while matomo-scoper reported success:
# - php-scoper hit Xdebug's nesting limit, swallowed the error and copied the file through
#   unprefixed while still printing "Successfully prefixed N files".
# - a plain `composer update` overwrote vendor/autoload.php with the stock Composer loader,
#   dropping the proxy that loads vendor/prefixed. The file is tracked, so it lands in the commit.
# - an empty php-scoper.phar (a download that failed partway) ran as a no-op with exit status 0,
#   leaving the old tree next to a new composer.lock.
#
# Usage: check_scoped_tree.sh <plugin-dir> <plugin-name> [allowed-namespace ...]
#
# The plugin directory must be a git checkout, because "did the tree change" is asked of git.

set -u

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <plugin-dir> <plugin-name> [allowed-namespace ...]" >&2
  exit 2
fi

plugin_dir="$1"
plugin_name="$2"
shift 2
allowed=("$@")

status=0

# GitHub ends an annotation property at a : or a , and decodes %.
annotation_file() {
  local file="$annotation_dir$1"
  file=${file//%/%25}
  file=${file//$'\r'/%0D}
  file=${file//$'\n'/%0A}
  file=${file//:/%3A}
  printf '%s' "${file//,/%2C}"
}

# GitHub reads an annotation's file from the workspace root, and the plugin can be checked out below it.
annotation_dir=''
if [ -n "${GITHUB_WORKSPACE:-}" ]; then
  annotation_dir="$(realpath --relative-to="$GITHUB_WORKSPACE" "$plugin_dir")/"
  [ "$annotation_dir" != ./ ] || annotation_dir=''
fi

if ! head -3 "$plugin_dir/vendor/autoload.php" 2>/dev/null | grep -q 'generated by the matomo-scoper tool'; then
  echo "::error file=$(annotation_file vendor/autoload.php)::vendor/autoload.php is not the matomo-scoper proxy, so vendor/prefixed would never be loaded."
  status=1
fi

prefix="Matomo\\Dependencies\\$plugin_name"
listing=$(mktemp)
# -a because the protobuf descriptor files under google/*/metadata are PHP files holding binary
# strings. Without it grep prints "Binary file ... matches" in place of their namespace line, and -I
# would skip them unchecked.
# A file copied through unprefixed keeps its own layout, so the declaration may be indented or follow
# <?php on the same line.
if ! grep -rhaoE --include='*.php' '^[[:space:]]*(<\?php[[:space:]]+)?namespace[[:space:]]+[A-Za-z0-9_\\]+' \
  "$plugin_dir/vendor/prefixed" > "$listing"; then
  echo "::error::Found no namespace declarations under vendor/prefixed, so it cannot have been scoped."
  rm -f "$listing"
  exit 1
fi

while IFS= read -r namespace; do
  case "$namespace" in
    "$prefix"|"$prefix\\"*) continue ;;
  esac
  permitted=0
  for name in "${allowed[@]}"; do
    if [ "$namespace" = "$name" ] || [[ "$namespace" == "$name\\"* ]]; then
      permitted=1
      break
    fi
  done
  if [ "$permitted" -eq 0 ]; then
    echo "::error::vendor/prefixed declares namespace $namespace, outside $prefix. Either the scoper skipped a file, or the namespace is deliberately left global and belongs in allowed-unprefixed-namespaces."
    status=1
  fi
done < <(sed -E 's/.*namespace[[:space:]]+//' "$listing" | sort -u)
rm -f "$listing"

# A warning, not a failure: a new string is as often an error message as a class name a patcher
# missed, and only reading the code around it tells the two apart.
strings=$(bash "$(dirname "${BASH_SOURCE[0]}")/find_new_unprefixed_strings.sh" "$plugin_dir" "$plugin_name")
strings_status=$?
if [ "$strings_status" -eq 0 ] && [ -n "$strings" ]; then
  # GitHub annotates only the first 10 warnings of a step, so the count is the tenth.
  annotated=0
  count=$(wc -l <<< "$strings")
  while IFS= read -r found; do
    # The string never holds ": ", and the path can.
    path=${found%: *}
    string=${found##*: }
    if [ "$annotated" -lt 9 ]; then
      echo "::warning file=$(annotation_file "$path")::vendor/prefixed gained the string $string without $prefix. If it builds a class name, a scoper.inc.php patcher has to prefix it, or the class is not found at runtime."
      annotated=$((annotated + 1))
      [ "$annotated" -lt 9 ] || [ "$count" -le 9 ] \
        || echo "::warning::vendor/prefixed gained $((count - 9)) more strings without $prefix, listed below."
    else
      echo "$path: $string"
    fi
  done <<< "$strings"
# 3 is a first scoping, with no earlier tree to compare with, so nothing is left unchecked.
elif [ "$strings_status" -ne 0 ] && [ "$strings_status" -ne 3 ]; then
  echo "::warning::vendor/prefixed was not checked for strings that name a scoped namespace without $prefix."
fi

# Packages rather than the whole file: composer.lock also changes on metadata alone (content-hash,
# plugin-api-version), and that legitimately leaves vendor/prefixed untouched. The commit counts too,
# because a branch dependency such as dev-main moves to a new commit without changing its version,
# but not the URLs, which change when a repository is renamed with the code left as it was. Only
# packages, not packages-dev: matomo-scoper prefixes nothing else.
lock_packages() {
  jq -S '[(.packages // [])[] | {name, version, source: .source.reference, dist: (.dist.reference // .dist.url)}]'
}
# Against HEAD, not the index, so a rebuild already staged still counts as a change.
if ! cmp -s <(git -C "$plugin_dir" show HEAD:./composer.lock | lock_packages) <(lock_packages < "$plugin_dir/composer.lock") \
  && git -C "$plugin_dir" diff --quiet HEAD -- vendor/prefixed \
  && [ -z "$(git -C "$plugin_dir" ls-files --others --exclude-standard -- vendor/prefixed)" ]; then
  echo "::error::composer.lock resolved different packages but vendor/prefixed did not change, so the scoped tree is stale."
  status=1
fi

exit "$status"
