#!/bin/bash
# Checks that a regenerated vendor/prefixed tree is really the output of this run.
#
# Every one of these has shipped, or nearly shipped, while matomo-scoper reported success:
# - php-scoper hit Xdebug's nesting limit, swallowed the error and copied the file through
#   unprefixed while still printing "Successfully prefixed N files".
# - a plain `composer update` overwrote vendor/autoload.php with the stock Composer loader,
#   dropping the proxy that loads vendor/prefixed. The file is tracked, so it lands in the commit.
# - an empty php-scoper.phar (a download that failed partway) ran as a no-op with exit status 0,
#   leaving the old tree next to a new composer.lock.
#
# Usage: check_scoped_tree.sh <plugin-dir> <plugin-name> [allowed-namespace ...]
#
# The plugin directory must be a git checkout, because "did the tree change" is asked of git.

set -u

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <plugin-dir> <plugin-name> [allowed-namespace ...]" >&2
  exit 2
fi

plugin_dir="$1"
plugin_name="$2"
shift 2
allowed=("$@")

status=0

if ! head -3 "$plugin_dir/vendor/autoload.php" 2>/dev/null | grep -q 'generated by the matomo-scoper tool'; then
  echo "::error file=vendor/autoload.php::vendor/autoload.php is not the matomo-scoper proxy, so vendor/prefixed would never be loaded."
  status=1
fi

prefix="Matomo\\Dependencies\\$plugin_name"
listing=$(mktemp)
# -I skips the protobuf descriptor files under google/*/metadata, which are PHP files holding binary
# strings; grep would otherwise print "Binary file ... matches" in place of the namespace line.
if ! grep -rhIE --include='*.php' '^namespace [A-Za-z0-9_\\]+' "$plugin_dir/vendor/prefixed" > "$listing"; then
  echo "::error::Found no namespace declarations under vendor/prefixed, so it cannot have been scoped."
  rm -f "$listing"
  exit 1
fi

while IFS= read -r namespace; do
  case "$namespace" in
    "$prefix"|"$prefix\\"*) continue ;;
  esac
  permitted=0
  for name in "${allowed[@]}"; do
    if [ "$namespace" = "$name" ] || [[ "$namespace" == "$name\\"* ]]; then
      permitted=1
      break
    fi
  done
  if [ "$permitted" -eq 0 ]; then
    echo "::error::vendor/prefixed declares namespace $namespace, outside $prefix. Either the scoper skipped a file, or the namespace is deliberately left global and belongs in allowed-unprefixed-namespaces."
    status=1
  fi
done < <(sed -E 's/^namespace ([A-Za-z0-9_\\]+).*/\1/' "$listing" | sort -u)
rm -f "$listing"

# Packages rather than the whole file: composer.lock also changes on metadata alone (content-hash,
# plugin-api-version), and that legitimately leaves vendor/prefixed untouched. Where they came from
# counts too, because a branch dependency such as dev-main moves to a new commit without changing
# its version. Only packages, not packages-dev: matomo-scoper prefixes nothing else.
lock_packages() {
  jq -S '[(.packages // [])[] | {name, version, source, dist}]'
}
# Against HEAD, not the index, so a rebuild already staged still counts as a change.
if ! cmp -s <(git -C "$plugin_dir" show HEAD:composer.lock | lock_packages) <(lock_packages < "$plugin_dir/composer.lock") \
  && git -C "$plugin_dir" diff --quiet HEAD -- vendor/prefixed \
  && [ -z "$(git -C "$plugin_dir" ls-files --others --exclude-standard -- vendor/prefixed)" ]; then
  echo "::error::composer.lock resolved different packages but vendor/prefixed did not change, so the scoped tree is stale."
  status=1
fi

exit "$status"
